debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.org.webrepo.sharespaceproject: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/space
    username: licsh
    password: cngkq123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always

---
spring:
  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:space;mode=mysql
#    driverClassName: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none